const products = () => [
    {
        _id: '1',
        name: 'Airpods Wireless Bluetooth Headphones',
        image: '/images/airpods.jpg',
        description: 'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working',
        brand: 'Apple',
        category: 'Electronics',
        price: 89.99,
        countInStock: 10,
        rating: 4.5,
        numReviews: 12,
    },
    {
        _id: '2',
        name: 'Alexa Smart Speaker',
        image: '/images/alexa.jpg',
        description: 'Voice-controlled smart speaker with Alexa, perfect for any room. Stream music, ask questions, control smart home devices, and more.',
        brand: 'Amazon',
        category: 'Electronics',
        price: 49.99,
        countInStock: 7,
        rating: 4.7,
        numReviews: 25,
    },
    {
        _id: '3',
        name: 'Canon DSLR Camera',
        image: '/images/camera.jpg',
        description: 'Capture stunning photos and videos with this DSLR camera. Features high-resolution sensor, multiple shooting modes, and built-in WiFi.',
        brand: 'Canon',
        category: 'Electronics',
        price: 599.99,
        countInStock: 5,
        rating: 4.8,
        numReviews: 15,
    },
    {
        _id: '4',
        name: 'Wireless Gaming Mouse',
        image: '/images/mouse.jpg',
        description: 'Ergonomic design and high-precision sensor for gaming. Wireless connectivity and customizable buttons for enhanced performance.',
        brand: 'Logitech',
        category: 'Electronics',
        price: 39.99,
        countInStock: 20,
        rating: 4.6,
        numReviews: 30,
    },
    {
        _id: '5',
        name: 'Smartphone with 5G Connectivity',
        image: '/images/phone.jpg',
        description: 'Latest smartphone with 5G connectivity, high-resolution display, and advanced camera system. Fast performance and long battery life.',
        brand: 'Samsung',
        category: 'Electronics',
        price: 999.99,
        countInStock: 8,
        rating: 4.4,
        numReviews: 22,
    },
    {
        _id: '6',
        name: 'PlayStation 5 Console',
        image: '/images/playstation.jpg',
        description: 'Next-gen gaming console with ultra-high-speed SSD, stunning graphics, and immersive gameplay. Includes DualSense wireless controller.',
        brand: 'Sony',
        category: 'Electronics',
        price: 499.99,
        countInStock: 3,
        rating: 4.9,
        numReviews: 40,
    }
]

export default products();